import 'package:flutter_gen/gen_l10n/app_localizations.dart';

extension AppLocalizationsExtension on AppLocalizations {
  String? getString(String key) {
    final Map<String, String> dynamicMap = {
      "depChooseDep": depChooseDep,
      "depSelectDep": depSelectDep,
      "depItFinance": depItFinance,
      "depNursing": depNursing,
      "depArchitectureEngineering": depArchitectureEngineering,
      "depArchitecture5yr": depArchitecture5yr,
      "depGameContent": depGameContent,
      "depBusiness": depBusiness,
      "depPolice": depPolice,
      "depActing": depActing,
      "depPerformingArts": depPerformingArts,
      "depTourismManagement": depTourismManagement,
      "depEducation": depEducation,
      "depFinanceInsurance": depFinanceInsurance,
      "depMechanical": depMechanical,
      "depAutomotiveMechanical": depAutomotiveMechanical,
      "depAgroFoodBusiness": depAgroFoodBusiness,
      "depDataEngineering": depDataEngineering,
      "depLibraryInfo": depLibraryInfo,
      "depLogisticsTrade": depLogisticsTrade,
      "depPhysicalTherapy": depPhysicalTherapy,
      "depPetIndustry": depPetIndustry,
      "depPetPlant": depPetPlant,
      "depRadiology": depRadiology,
      "depLaw": depLaw,
      "depHealthAdmin": depHealthAdmin,
      "depRealEstate": depRealEstate,
      "depSocialWelfare": depSocialWelfare,
      "depIndustrialEngineering": depIndustrialEngineering,
      "depIndustrialDesign": depIndustrialDesign,
      "depCounseling": depCounseling,
      "depSports": depSports,
      "depFireSafety": depFireSafety,
      "depSmartMedia": depSmartMedia,
      "depVisualDesign": depVisualDesign,
      "depFoodNutrition": depFoodNutrition,
      "depChemistryMaterials": depChemistryMaterials,
      "depTheologyPraise": depTheologyPraise,
      "depHistoryContent": depHistoryContent,
      "depEnglish": depEnglish,
      "depFilmBroadcast": depFilmBroadcast,
      "depArtTherapy": depArtTherapy,
      "depCulinaryService": depCulinaryService,
      "depExercisePrescription": depExercisePrescription,
      "depWebtoonComics": depWebtoonComics,
      "depAi": depAi,
      "depJapanese": depJapanese,
      "depOccupationalTherapy": depOccupationalTherapy,
      "depRehabilitation": depRehabilitation,
      "depElectricalElectronic": depElectricalElectronic,
      "depInfoCommunication": depInfoCommunication,
      "depChinese": depChinese,
      "depStartupFinance": depStartupFinance,
      "depFootball": depFootball,
      "depEcoVehicle": depEcoVehicle,
      "depComputer": depComputer,
      "depTaekwondo": depTaekwondo,
      "depCivilEnvironment": depCivilEnvironment,
      "depFashion": depFashion,
      "depKoreanLanguage": depKoreanLanguage,
      "depKoreanCuisine": depKoreanCuisine,
      "depPublicAdmin": depPublicAdmin,
      "depHotel": depHotel,
      "depEnvironmentLife": depEnvironmentLife,
      "depAccountingTax": depAccountingTax,
      "depMusic": depMusic,
    };

    return dynamicMap[key];
  }
}

